// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (for actual values), then .env (for defaults)
// This matches Next.js behavior where .env.local overrides .env
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Seed script for creating demo user account
    seed: "bun prisma/seed.ts",
  },
  // For migrations: use Neon Postgres (same as runtime)
  datasource: {
    url: process.env.POSTGRES_PRISMA_URL || process.env.DATABASE_URL || "file:./dev.db",
  },
});


